#include "SerialCommandHandler.h"

/*
tempshow
+ 32 degC

tempshow 0
    tempshow OFF
        Phasenmodus OFF

            tempshow 1
    tempshow   1 Sekunden Phasenmodus OFF

        trace
            trace OFF Interne Automatenzustaende ausgeben [0 oder 1]

    trace 0
    trace OFF Interne Automatenzustaende ausgeben [0 oder 1]

    trace 1
    trace ON Interne Automatenzustaende ausgeben [0 oder 1]

    debug 0
    trace OFF Debugging Informationen  ausgeben [0 oder 1]

    debug
        trace OFF Debugging Informationen  ausgeben [0 oder 1]

    stop
        stop

            sold
                sold

                    temptrace 1
    tempshow   1 Sekunden Phasenmodus ON

        temptrace 0
    tempshow OFF
        Phasenmodus ON

            temptrace
    + 33 degC

        tempoffset
            tempoffset-   8 Temperatur Justage [-30..30] Grad
              tempoffset 0
          tempoffset    0 Temperatur Justage [-30..30] Grad

              phttemp
                  phttemp  130 Preheat Temperatur: [0..254] degC
                                                       phttemp 131
                                                   phttemp  131 Preheat Temperatur: [0..254] degC

                                                                                        phttime
                                                                                            phttime  100
Preheat Zeit: [0..65534] Sekunden phttime 101 phttime  101 Preheat Zeit: [0..65534] Sekunden

                                                                                                                                                      phtpwr
                                                                                                                                                          phtpwr  100 Preheat Leistung: [0..254] %
                                                                                                                                                                                        phtpwr 101
                                                                                                                                                                                        phtpwr  101 Preheat Leistung: [0..254] %

                                                                                                                                                                                                                      soaktemp
                                                                                                                                                                                                                          soaktemp  150 Soak Temperatur: [0..254] degC
                                                                                                                                                                                                                                                             soaktemp 151
                                                                                                                                                                                                                                                         soaktemp  151 Soak Temperatur: [0..254] degC

                                                                                                                                                                                                                                                                                            soaktime
                                                                                                                                                                                                                                                                                                soaktime  120 Soak Zeit: [0..65534] Sekunden
                                                                                                                                                                                                                                                                                                                             soaktime 121
                                                                                                                                                                                                                                                                                                                         soaktime  121 Soak Zeit: [0..65534] Sekunden

                                                                                                                                                                                                                                                                                                                                                      soakpwr
                                                                                                                                                                                                                                                                                                                                                          soakpwr    5 Soak Leistung: [0..254] %
                                                                                                                                                                                                                                                                                                                                                                                    soakpwr 100
                                                                                                                                                                                                                                                                                                                                                                                    soakpwr  100 Soak Leistung: [0..254] %

                                                                                                                                                                                                                                                                                                                                                                                                                reflowtemp
                                                                                                                                                                                                                                                                                                                                                                                                                    reflowtemp  210 Reflow Temperatur: [0..254] degC
                                                                                                                                                                                                                                                                                                                                                                                                                                                           reflowtemp 211
                                                                                                                                                                                                                                                                                                                                                                                                                                                       reflowtemp  211 Reflow Temperatur: [0..254] degC

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              reflowtime
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  reflowtime  100 Reflow Zeit: [0..65534] Sekunden
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   reflowtime 101
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               reflowtime  101 Reflow Zeit: [0..65534] Sekunden

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reflowpwr
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reflowpwr  100 Reflow Leistung: [0..254] %
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reflowpwr 101
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reflowpwr  101 Reflow Leistung: [0..254] %

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dwelltemp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dwelltemp  242 Dwell Temperatur: [0..254] degC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             dwelltemp 243
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         dwelltemp  243 Dwell Temperatur: [0..254] degC

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              dwelltime
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dwelltime   20 Dwell Zeit: [0..65534] Sekunden
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dwelltime 21
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dwelltime   21 Dwell Zeit: [0..65534] Sekunden

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          dwellpwr
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              dwellpwr  100 Dwell Leistung: [0..254] %
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dwellpwr 101
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dwellpwr  101 Dwell Leistung: [0..254] %

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          hj
# Command not found
# use "help"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
